### ISSUE TITLE
`sub-LC164`: IndexError: list index out of range

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/spine-park#36]
SCT: 517cc66596db50a310ddc0bdf8985fbbe54405a4
Script: 8e66fb444aa1a887babaf2fc2d56b966acbe801e

<details><summary>Terminal output</summary>

```console

--
Spinal Cord Toolbox (git-jca/4527-register-template-step0-517cc66596db50a310ddc0bdf8985fbbe54405a4*)

sct_check_dependencies -short
--


SYSTEM INFORMATION
------------------
SCT info:
- version: git-jca/4527-register-template-step0-517cc66596db50a310ddc0bdf8985fbbe54405a4*
- path: /home/GRAMES.POLYMTL.CA/p101317/code/spinalcordtoolbox
OS: linux (Linux-6.5.0-41-generic-x86_64-with-glibc2.38)
CPU cores: Available: 128, Used by ITK functions: 1
RAM: Total: 257572MB, Used: 4596MB, Available: 247044MB
sending incremental file list
sub-LC164/
sub-LC164/anat/
sub-LC164/anat/sub-LC164_T1map.json
sub-LC164/anat/sub-LC164_T1map.nii.gz
sub-LC164/anat/sub-LC164_T2.json
sub-LC164/anat/sub-LC164_T2.nii.gz
sub-LC164/anat/sub-LC164_UNIT1.json
sub-LC164/anat/sub-LC164_UNIT1.nii.gz
sub-LC164/anat/sub-LC164_mt-off_MTS.json
sub-LC164/anat/sub-LC164_mt-off_MTS.nii.gz
sub-LC164/anat/sub-LC164_mt-on_MTS.json
sub-LC164/anat/sub-LC164_mt-on_MTS.nii.gz
sub-LC164/dwi/
sub-LC164/dwi/sub-LC164_chunk-1_DWI.bval
sub-LC164/dwi/sub-LC164_chunk-1_DWI.bvec
sub-LC164/dwi/sub-LC164_chunk-1_DWI.json
sub-LC164/dwi/sub-LC164_chunk-1_DWI.nii.gz
sub-LC164/dwi/sub-LC164_chunk-2_DWI.bval
sub-LC164/dwi/sub-LC164_chunk-2_DWI.bvec
sub-LC164/dwi/sub-LC164_chunk-2_DWI.json
sub-LC164/dwi/sub-LC164_chunk-2_DWI.nii.gz
sub-LC164/dwi/sub-LC164_chunk-3_DWI.bval
sub-LC164/dwi/sub-LC164_chunk-3_DWI.bvec
sub-LC164/dwi/sub-LC164_chunk-3_DWI.json
sub-LC164/dwi/sub-LC164_chunk-3_DWI.nii.gz

sent 106.42M bytes  received 454 bytes  70.94M bytes/sec
total size is 106.40M  speedup is 1.00
👉 Processing: sub-LC164_T2

Looking for manual segmentation: /home/GRAMES.POLYMTL.CA/p101317/lydia/CENIR_ICEBERG_spine_BIDS/derivatives/labels/sub-LC164/anat/sub-LC164_T2_seg.nii.gz
Not found. Proceeding with automatic segmentation.

--
Spinal Cord Toolbox (git-jca/4527-register-template-step0-517cc66596db50a310ddc0bdf8985fbbe54405a4*)

sct_deepseg -i sub-LC164_T2.nii.gz -task seg_sc_contrast_agnostic -qc /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240618_122926/qc -qc-subject sub-LC164
--

Model 'model_seg_sc_contrast_agnostic_softseg_monai' is up to date (Source: https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/download/v2.4/model_soft_bin_20240425-170840.zip)
Creating temporary folder (/tmp/sct_2024-06-18_12-29-41_sct_deepseg_kouigzb3)
Copied sub-LC164_T2.nii.gz to /tmp/sct_2024-06-18_12-29-41_sct_deepseg_kouigzb3/sub-LC164_T2.nii.gz
Starting inference...
Inference done.
Total inference time: 0 minute(s) 29 seconds
Saving results to: /tmp/sct_2024-06-18_12-29-41_sct_deepseg_kouigzb3/sub-LC164_T2_seg.nii.gz
[33mImage header specifies datatype 'float32', but array is of type '<class 'numpy.uint8'>'. Header metadata will be overwritten to use '<class 'numpy.uint8'>'.[0m

*** Generating Quality Control (QC) html report ***
Resample images to 0.600000x0.600000 vox
[33mConverting image from type 'int16' to type 'float64' for spline interpolation[0m
[33mConverting image from type 'uint8' to type 'float64' for linear interpolation[0m
Find the center of each slice
/home/GRAMES.POLYMTL.CA/p101317/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/scipy/ndimage/_measurements.py:1542: RuntimeWarning: invalid value encountered in scalar divide
  results = [sum(input * grids[dir].astype(float), labels, index) / normalizer
Successfully generated the QC results in /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240618_122926/qc/_json/qc_2024_06_18_123015.841357.json

To see the results in a browser, type:
xdg-open /home/GRAMES.POLYMTL.CA/p101317/lydia/results_20240618_122926/qc/index.html


Done! To view results, type:
fsleyes sub-LC164_T2.nii.gz -cm greyscale sub-LC164_T2_seg.nii.gz -cm red -a 70.0 &

Looking for manual label: /home/GRAMES.POLYMTL.CA/p101317/lydia/CENIR_ICEBERG_spine_BIDS/derivatives/labels/sub-LC164/anat/sub-LC164_T2_label-disc.nii.gz
Found! Using manual labels.
sending incremental file list
sub-LC164_T2_label-disc.nii.gz

sent 465 bytes  received 35 bytes  1.00K bytes/sec
total size is 57.42K  speedup is 114.84

--
Spinal Cord Toolbox (git-jca/4527-register-template-step0-517cc66596db50a310ddc0bdf8985fbbe54405a4*)

sct_label_utils -i sub-LC164_T2_seg.nii.gz -disc sub-LC164_T2_label-disc.nii.gz -o sub-LC164_T2_seg_labeled.nii.gz
--

Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p101317/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_label_utils.py", line 424, in <module>
    main(sys.argv[1:])
  File "/home/GRAMES.POLYMTL.CA/p101317/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_label_utils.py", line 280, in main
    out = sct_labels.labelize_from_discs(img, ref)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/spinalcordtoolbox/spinalcordtoolbox/labels.py", line 242, in labelize_from_discs
    if z > coordinates_ref[0].z:
IndexError: list index out of range
```

</details>

**Comment by jcohenadad** [comment]
Segmentation looks good:
![image](https://github.com/sct-pipeline/spine-park/assets/2482071/b2cae6da-55bf-4bb4-aa6a-04361953cc02)

**Comment by jcohenadad** [comment]
OK, the problem is that the manual disc label file is empty:
```console
julien-macbook:~/code/spinalcordtoolbox $ sct_label_utils -i /Users/julien/temp/Lydia/results_20240618_140932/sub-LC164/anat/sub-LC164_T2_label-disc.nii.gz -display

--
Spinal Cord Toolbox (git-jca/4527-register-template-step0-517cc66596db50a310ddc0bdf8985fbbe54405a4)

sct_label_utils -i /Users/julien/temp/Lydia/results_20240618_140932/sub-LC164/anat/sub-LC164_T2_label-disc.nii.gz -display
--

All labels (useful syntax):

```

I forgot if @kaonashi22 you sent me the label, and if so, you might want to fix it

**Comment by Kaonashi22** [comment]
I think I only shared six subjects with you; here are their vertebral labels.
If you have more subjects, I can send you their labels

[derivatives.zip](https://github.com/user-attachments/files/15890942/derivatives.zip)

**Comment by jcohenadad** [comment]
> I think I only shared six subjects with you; here are their vertebral labels. If you have more subjects, I can send you their labels

I'll only re-run the pipeline if you experience specific issues, @Kaonashi22. We can consider this issue closed since it has to do with manual labels.

**Comment by Kaonashi22** [comment]
I can run the same script as before with the same sct version?

**Comment by jcohenadad** [comment]
As discussed in https://github.com/sct-pipeline/spine-park/issues/33#issuecomment-2174715440, once the PR is merged you can resume the experiments.
