### ISSUE TITLE
Error with dwi processing 

### ISSUE THREAD

**Issue by Kaonashi22** [sct-pipeline/spine-park#50]
I had this error with one subject while processing the diffusion:

_Register. Loop across Z (note: there is only one Z if orientation is axial)
Traceback (most recent call last):
  File "/export02/data/lydiac/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_dmri_moco.py", line 232, in <module>
    main(sys.argv[1:])
  File "/export02/data/lydiac/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_dmri_moco.py", line 217, in main
    fname_output_image = moco_wrapper(param)
  File "/export02/data/lydiac/spinalcordtoolbox/spinalcordtoolbox/moco.py", line 340, in moco_wrapper
    file_mat_datasub_group, _ = moco(param_moco)
  File "/export02/data/lydiac/spinalcordtoolbox/spinalcordtoolbox/moco.py", line 609, in moco
    failed_transfo[it] = register(param, file_data_splitZ_splitT[it], file_target_splitZ[iz], file_mat[iz][it],
  File "/export02/data/lydiac/spinalcordtoolbox/spinalcordtoolbox/moco.py", line 753, in register
    status, output = run_proc(cmd, verbose=1 if param.verbose == 2 else 0, env=env, **kw)
  File "/export02/data/lydiac/spinalcordtoolbox/spinalcordtoolbox/utils/sys.py", line 342, in run_proc
    raise RuntimeError(output)
RuntimeError: Exception caught:
itk::ExceptionObject (0x22a6940)
Location: "unknown"
File: /__w/build_ANTs/build_ANTs/antsbin/staging/include/ITK-5.1/itkMattesMutualInformationImageToImageMetricv4.hxx
Line: 312
Description: itk::ERROR: MattesMutualInformationImageToImageMetricv4(0x2260530): Joint PDF summed to zero_

[err.batch_processing_sub-FP292.log](https://github.com/user-attachments/files/16143379/err.batch_processing_sub-FP292.log)

Otherwise, it worked well for the rest of the subjects!

**Comment by jcohenadad** [comment]
Can pls send me this subject?

**Comment by jcohenadad** [comment]
Can you re-run with https://github.com/sct-pipeline/spine-park/commit/924e332c3b4836baa087ea740a7837120d0b7cbf?

**Comment by Kaonashi22** [comment]
Thank you, I'm re-running the subject

**Comment by Kaonashi22** [comment]
It worked well, thank you!

**Comment by jcohenadad** [comment]
great! closing then
